FROM joxit/docker-registry-ui:2.0

LABEL maintainer="Jianwei Mao <maojianwei2012@126.com>"

ENV NGINX_PROXY_PASS_URL http://127.0.0.1:5000
ENV DELETE_IMAGES true
ENV REGISTRY_TITLE "Mao Docker Registry GUI"
