apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mao-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: pi-dpdk.maojianwei.com
    path: "/home/mao/dataDisk/docker-registry"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mao-pvc
spec:
  volumeName: nfs-mao-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mao-registry-gui
  template:
    metadata:
      labels:
        app: mao-registry-gui
    spec:
      containers:
      - name: registry
        image: maojianwei2020/registry:2.7.1.9-mao
        ports:
          - name: register-port
            containerPort: 5000
        volumeMounts:
          - name: nfs-registry
            mountPath: "/var/lib/registry"
      - name: gui
        image: maojianwei2020/registry-gui:2.3-mao
#        env:
#          - name: DELETE_IMAGES
#            value: "false"
#          - name: REGISTRY_TITLE
#            value: "Mao Docker Registry GUI"
        ports:
          - name: gui-port
            containerPort: 80
      volumes:
      - name: nfs-registry
        persistentVolumeClaim:
          claimName: nfs-mao-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: registry-gui-service
spec:
  type: NodePort
  selector:
    app: mao-registry-gui
  ports:
  - name: docker-images
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30050
  - name: gui
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
    
